### ISSUE TITLE
Book feedback (long overdue)

### ISSUE THREAD

**Issue by sffc** [rust-diplomat/book#3]
Working through my review backlog and leaving comments on the Diplomat Book was on it.

1. basics.md: Why is `create` renamed to `create_` in C++? I thought we chose `create` because it didn't need to be mangled, unlike `new`
2. types.md: Very much out of date
3. opaque.md: Visibility of `ffi::MyCollection` -- should it be `pub`? I remember making a change that stopped Diplomat from exporting non-public symbols.
4. structs.md: I thought structs in JS were being eagerly converged to objects, not classes with getters. Did this change?

**Comment by Manishearth** [comment]
Mostly fixed in https://github.com/rust-diplomat/book/pull/4, fixed the last point in https://github.com/rust-diplomat/book/commit/667f8213d050dbe5685feb9c9eccc2e88838289a
